// npm run env:local
// Writes .env.local from the running local Supabase stack (`supabase start`).
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";

const raw = execFileSync("npx", ["supabase", "status", "-o", "env"], { encoding: "utf8" });
const vars = Object.fromEntries(
  raw
    .split("\n")
    .map((line) => /^([A-Z_]+)="?(.*?)"?$/.exec(line.trim()))
    .filter((m): m is RegExpExecArray => Boolean(m))
    .map((m) => [m[1], m[2]]),
);

const required = ["API_URL", "ANON_KEY", "SERVICE_ROLE_KEY"];
const missing = required.filter((k) => !vars[k]);
if (missing.length) {
  console.error(`supabase status did not report ${missing.join(", ")}. Is \`npx supabase start\` running?`);
  process.exit(1);
}

if (existsSync(".env.local") && !process.argv.includes("--force")) {
  console.error(".env.local already exists. Re-run with --force to overwrite it.");
  process.exit(1);
}

writeFileSync(
  ".env.local",
  [
    "# Generated by npm run env:local from `supabase status`.",
    `NEXT_PUBLIC_SUPABASE_URL=${vars.API_URL}`,
    `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${vars.ANON_KEY}`,
    `SUPABASE_SERVICE_ROLE_KEY=${vars.SERVICE_ROLE_KEY}`,
    "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
    "",
  ].join("\n"),
);
console.log("Wrote .env.local for the local Supabase stack.");
